version: '1.0.{build}'

image: Visual Studio 2019

platform:
 - x64

configuration:
 - Release
 - Debug

install:
 - git submodule update --init --recursive

before_build:
 - cmake -G "Visual Studio 16 2019" -A x64 .

skip_branch_with_pr: true
max_jobs: 1

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln