version: '1.0.{build}'

image: Visual Studio 2019

platform:
 - x64

configuration:
 - Release
 - Debug

install:
 - git submodule update --init --recursive

before_build:
 - powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
 - cmake -G "Visual Studio 16 2019" -A x64 .
 - powershell Get-Content beast.vcxproj
 - powershell Get-Content galib.vcxproj

artifacts:
 - path: '**/*'
   name: AllFiles

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

