version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Pull git submodules
          command: |
            git submodule init
            git submodule update
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y clang-tidy lcov ccache
      - run:
          name: Create build directory
          command: |
            mkdir -p build
      - run:
          name: Setup cmake
          command: |
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug ..
      - run:
          name: Build
          command: |
            cd build
            make
      - persist_to_workspace:
          root: .
          paths:
            - "."
  test:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute tests
          command: |
            cd build
            make test
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y npm lcov ccache
      - run:
          name: Generate coverage report
          command: |
            cd build
            make coverage
      - coveralls/upload:
          path_to_lcov: ./build/coverage.info
          token: COVERALLS_REPO_TOKEN
  sonarqube:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            python3 -m pip install compiledb
      - run:
          name: Checkout Sonar Tooling
          command: |
            git pull https://github.com/SonarSource/sonar-training-examples.git
            chmod +x sonar-training-examples/cpp-scan/convert-compile-commands.py
      - run:
          name: Convert Database
          command: |
            compiledb make -B
            ./sonar-training-examples/cpp-scan/convert-compile-commands.py build/compile_commands.json bw-output
      - attach_workspace:
          at: .
      - sonarcloud/scan

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonarqube:
          context: SonarCloud
          requires:
            - build
