version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Pull git submodules
          command: |
            git submodule update
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y clang-tidy
      - run:
          name: Create build directory
          command: |
            mkdir -p build
      - run:
          name: Setup cmake
          command: |
            cd build
            cmake ..
      - run:
          name: Build
          command: |
            cd build
            make
      - persist_to_workspace:
          root: .
          paths:
            - "build"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute tests
          command:
            cd build
            make test

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
          