version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Create build directory
          command: |
            mkdir -p build
      - run:
          name: Setup cmake
          command: |
            cd build
            cmake ..
      - persist_to_workspace:
          root: .
          paths:
            - "build"

workflows:
  say-hello-workflow:
    jobs:
      - build
