#include <beast/program_c_codegen.hpp>

// Standard
#include <iomanip>
#include <sstream>

namespace beast {

namespace {

constexpr uint32_t kDefaultMemoryVariables = 64;
constexpr uint32_t kDefaultStackCapacity = 256;
constexpr uint32_t kDefaultMaxSteps = 1000000;

/// Render the bytecode as a comma-separated hex byte initialiser, wrapped at 12 bytes
/// per line so the generated source stays diff-friendly. Each line starts with two
/// spaces of indentation so it nests under the opening brace of the array literal.
std::string renderBytecodeArray(const std::vector<unsigned char>& bytecode) {
  std::ostringstream out;
  for (size_t i = 0; i < bytecode.size(); ++i) {
    if (i % 12 == 0) {
      out << (i == 0 ? "  " : "\n  ");
    }
    out << "0x" << std::hex << std::setw(2) << std::setfill('0')
        << static_cast<unsigned>(bytecode[i]);
    if (i + 1 < bytecode.size()) {
      out << ", ";
    }
  }
  return out.str();
}

/// The C VM template. Bracketed placeholders are substituted before emission:
///   {{BANNER}}        -- optional human-readable comment block (or empty)
///   {{MEM_SIZE}}      -- number of variables exposed to the program
///   {{STACK_SIZE}}    -- stack capacity (per-stack)
///   {{MAX_STEPS}}     -- step budget for the generated main()
///   {{PROGRAM_BYTES}} -- the embedded bytecode array initialiser
///
/// Kept as a single raw string so the generated output is a faithful copy of the
/// template -- diffs in the template are diffs in every generated file.
const char* const kCRuntimeTemplate = R"CTEMPLATE(/*
 * Auto-generated by beast-compose / Program Collection.
{{BANNER}} *
 * Usage:
 *   cc program.c -o program
 *   ./program [--var IDX=VAL ...] [--steps N]
 *
 * Examples:
 *   ./program --var 0=42 --var 8=0x428a2f98 --steps 200000
 *   ./program --var 0:42 --var 8:0x428a2f98          (':' and '=' both work)
 *
 * On exit the program prints every variable's final value as both decimal and hex.
 * The Stack and string-table opcodes are implemented but bounded by the compile-time
 * constants below; system calls and subroutines are recognised but stubbed -- they
 * print a one-line warning to stderr and continue, so the program still runs even
 * if the evolved genome accidentally landed on one of them.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define MEM_SIZE   {{MEM_SIZE}}
#define STACK_SIZE {{STACK_SIZE}}
#define STRING_TABLE_SIZE 32
#define STRING_TABLE_ITEM_MAX 256
#define MAX_STEPS  {{MAX_STEPS}}

static const unsigned char PROGRAM[] = {
{{PROGRAM_BYTES}}
};
static const int PROGRAM_LEN = (int)(sizeof(PROGRAM) / sizeof(PROGRAM[0]));

/* Variable space. Initialised to 0; the user can override any subset via CLI. */
static int32_t vars[MEM_SIZE];
/* Single global stack -- the BEAST VM has per-stack opcodes addressed by var index,
 * but for the generated standalone program we collapse them into one stack since
 * separating them would balloon the runtime for little practical gain. */
static int32_t stack[STACK_SIZE];
static int stack_top = 0;  /* index of next free slot */
/* String table: each entry is null-terminated; empty entries are zero-length. */
static char string_table[STRING_TABLE_SIZE][STRING_TABLE_ITEM_MAX];
/* Program counter; opcode dispatch reads at PROGRAM[pc] and advances. */
static int pc = 0;

static int32_t read_i32(int offset) {
  return (int32_t)((uint32_t)PROGRAM[offset]
                 | ((uint32_t)PROGRAM[offset + 1] << 8)
                 | ((uint32_t)PROGRAM[offset + 2] << 16)
                 | ((uint32_t)PROGRAM[offset + 3] << 24));
}
static int16_t read_i16(int offset) {
  return (int16_t)((uint16_t)PROGRAM[offset]
                 | ((uint16_t)PROGRAM[offset + 1] << 8));
}
static int8_t read_i8(int offset) { return (int8_t)PROGRAM[offset]; }

static int32_t consume_i32(void) { int32_t v = read_i32(pc); pc += 4; return v; }
static int16_t consume_i16(void) { int16_t v = read_i16(pc); pc += 2; return v; }
static int8_t  consume_i8(void)  { int8_t  v = read_i8(pc);  pc += 1; return v; }

/* Clamp a variable index into [0, MEM_SIZE-1] so a malformed/out-of-range index can't
 * blow up the generated program at runtime. The C++ VM throws on out-of-range; here
 * we'd rather degrade gracefully so the user can still see "what the program tried
 * to do" in the variable dump. */
static int32_t* var_at(int32_t idx) {
  if (idx < 0) idx = 0;
  if (idx >= MEM_SIZE) idx = MEM_SIZE - 1;
  return &vars[idx];
}

static void push(int32_t value) {
  if (stack_top >= STACK_SIZE) return; /* drop on overflow */
  stack[stack_top++] = value;
}
static int32_t pop(void) {
  if (stack_top <= 0) return 0;
  return stack[--stack_top];
}

/* Rotate helpers (right/left). Mask the shift count to avoid UB on amount == 0 or 32. */
static uint32_t rotl32(uint32_t v, uint32_t n) {
  n &= 31U;
  return n == 0 ? v : (v << n) | (v >> (32U - n));
}
static uint32_t rotr32(uint32_t v, uint32_t n) {
  n &= 31U;
  return n == 0 ? v : (v >> n) | (v << (32U - n));
}

/* Returns 1 if the VM advanced one step, 0 on Terminate or unknown/truncated opcode.
 * Loops over this in main() until it returns 0 or MAX_STEPS is hit. */
static int step(void) {
  if (pc < 0 || pc >= PROGRAM_LEN) return 0;
  int8_t op = consume_i8();
  switch ((unsigned char)op) {
  case 0x00: /* NoOp */
    return 1;
  case 0x01: { /* LoadMemorySizeIntoVariable */
    int32_t v = consume_i32(); (void)consume_i8();
    *var_at(v) = (int32_t)MEM_SIZE;
    return 1;
  }
  case 0x02: { /* LoadCurrentAddressIntoVariable */
    int32_t v = consume_i32(); (void)consume_i8();
    *var_at(v) = pc;
    return 1;
  }
  case 0x03: { /* Terminate */
    (void)consume_i8();
    return 0;
  }
  case 0x04: { /* TerminateWithVariableReturnCode */
    int32_t v = consume_i32(); (void)consume_i8();
    /* The return code lives in var[v]; main() picks it up from there after we stop. */
    *var_at(0) = *var_at(v); /* mirror to var[0] so it's visible in the dump */
    return 0;
  }
  case 0x05: { /* PerformSystemCall (stubbed) */
    (void)consume_i8(); (void)consume_i8(); (void)consume_i32(); (void)consume_i8();
    fprintf(stderr, "warning: PerformSystemCall is not implemented in the generated runtime\n");
    return 1;
  }
  case 0x06: { /* LoadRandomValueIntoVariable */
    int32_t v = consume_i32(); (void)consume_i8();
    *var_at(v) = (int32_t)rand();
    return 1;
  }
  case 0x07: { /* DeclareVariable -- type-only declaration; runtime no-op */
    (void)consume_i32(); (void)consume_i8();
    return 1;
  }
  case 0x08: { /* SetVariable */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t value = consume_i32();
    *var_at(v) = value;
    return 1;
  }
  case 0x09: { /* UndeclareVariable -- zero out the variable */
    int32_t v = consume_i32();
    *var_at(v) = 0;
    return 1;
  }
  case 0x0a: { /* CopyVariable src -> dst */
    int32_t src = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = *var_at(src);
    return 1;
  }
  case 0x0b: { /* SwapVariables */
    int32_t a = consume_i32(); (void)consume_i8();
    int32_t b = consume_i32(); (void)consume_i8();
    int32_t tmp = *var_at(a); *var_at(a) = *var_at(b); *var_at(b) = tmp;
    return 1;
  }
  case 0x0c: { /* AddConstantToVariable */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t c = consume_i32();
    *var_at(v) += c;
    return 1;
  }
  case 0x0d: { /* AddVariableToVariable src -> dst */
    int32_t src = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) += *var_at(src);
    return 1;
  }
  case 0x0e: { /* SubtractConstantFromVariable */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t c = consume_i32();
    *var_at(v) -= c;
    return 1;
  }
  case 0x0f: { /* SubtractVariableFromVariable src -> dst */
    int32_t src = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) -= *var_at(src);
    return 1;
  }
  case 0x10: { /* CompareIfVariableGtConstant -> dst */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t c = consume_i32(); int32_t dst = consume_i32();
    *var_at(dst) = (*var_at(v) > c) ? 1 : 0;
    return 1;
  }
  case 0x11: { /* CompareIfVariableLtConstant */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t c = consume_i32(); int32_t dst = consume_i32();
    *var_at(dst) = (*var_at(v) < c) ? 1 : 0;
    return 1;
  }
  case 0x12: { /* CompareIfVariableEqConstant */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t c = consume_i32(); int32_t dst = consume_i32();
    *var_at(dst) = (*var_at(v) == c) ? 1 : 0;
    return 1;
  }
  case 0x13: { /* CompareIfVariableGtVariable */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = (*var_at(a) > *var_at(b)) ? 1 : 0;
    return 1;
  }
  case 0x14: { /* CompareIfVariableLtVariable */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = (*var_at(a) < *var_at(b)) ? 1 : 0;
    return 1;
  }
  case 0x15: { /* CompareIfVariableEqVariable */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = (*var_at(a) == *var_at(b)) ? 1 : 0;
    return 1;
  }
  case 0x16: { /* GetMaxOfVariableAndConstant */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t c = consume_i32(); int32_t dst = consume_i32();
    int32_t a = *var_at(v); *var_at(dst) = (a > c) ? a : c;
    return 1;
  }
  case 0x17: { /* GetMinOfVariableAndConstant */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t c = consume_i32(); int32_t dst = consume_i32();
    int32_t a = *var_at(v); *var_at(dst) = (a < c) ? a : c;
    return 1;
  }
  case 0x18: { /* GetMaxOfVariableAndVariable */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    int32_t va = *var_at(a), vb = *var_at(b);
    *var_at(dst) = (va > vb) ? va : vb;
    return 1;
  }
  case 0x19: { /* GetMinOfVariableAndVariable */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    int32_t va = *var_at(a), vb = *var_at(b);
    *var_at(dst) = (va < vb) ? va : vb;
    return 1;
  }
  case 0x1a: { /* ModuloVariableByConstant */
    int32_t v = consume_i32(); (void)consume_i8(); int32_t c = consume_i32();
    if (c != 0) *var_at(v) %= c;
    return 1;
  }
  case 0x1b: { /* ModuloVariableByVariable */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    int32_t vb = *var_at(b);
    if (vb != 0) *var_at(a) %= vb;
    return 1;
  }
  case 0x1c: { /* BitShiftVariableLeft */
    int32_t v = consume_i32(); (void)consume_i8(); int8_t bits = consume_i8();
    *var_at(v) = (int32_t)((uint32_t)*var_at(v) << ((unsigned)bits & 31U));
    return 1;
  }
  case 0x1d: { /* BitShiftVariableRight */
    int32_t v = consume_i32(); (void)consume_i8(); int8_t bits = consume_i8();
    *var_at(v) = (int32_t)((uint32_t)*var_at(v) >> ((unsigned)bits & 31U));
    return 1;
  }
  case 0x1e: { /* BitWiseInvertVariable */
    int32_t v = consume_i32(); (void)consume_i8();
    *var_at(v) = ~*var_at(v);
    return 1;
  }
  case 0x1f: { /* BitWiseAndTwoVariables a, b -> b */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    *var_at(b) &= *var_at(a);
    return 1;
  }
  case 0x20: { /* BitWiseOrTwoVariables */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    *var_at(b) |= *var_at(a);
    return 1;
  }
  case 0x21: { /* BitWiseXorTwoVariables */
    int32_t a = consume_i32(); (void)consume_i8(); int32_t b = consume_i32(); (void)consume_i8();
    *var_at(b) ^= *var_at(a);
    return 1;
  }
  case 0x22: { /* RotateVariableLeft */
    int32_t v = consume_i32(); (void)consume_i8(); int8_t bits = consume_i8();
    *var_at(v) = (int32_t)rotl32((uint32_t)*var_at(v), (uint32_t)(unsigned)bits);
    return 1;
  }
  case 0x23: { /* RotateVariableRight */
    int32_t v = consume_i32(); (void)consume_i8(); int8_t bits = consume_i8();
    *var_at(v) = (int32_t)rotr32((uint32_t)*var_at(v), (uint32_t)(unsigned)bits);
    return 1;
  }
  case 0x24: { /* VariableBitShiftVariableLeft target by amount-var */
    int32_t t = consume_i32(); (void)consume_i8(); int32_t a = consume_i32(); (void)consume_i8();
    *var_at(t) = (int32_t)((uint32_t)*var_at(t) << ((unsigned)*var_at(a) & 31U));
    return 1;
  }
  case 0x25: { /* VariableBitShiftVariableRight */
    int32_t t = consume_i32(); (void)consume_i8(); int32_t a = consume_i32(); (void)consume_i8();
    *var_at(t) = (int32_t)((uint32_t)*var_at(t) >> ((unsigned)*var_at(a) & 31U));
    return 1;
  }
  case 0x26: { /* VariableRotateVariableLeft */
    int32_t t = consume_i32(); (void)consume_i8(); int32_t a = consume_i32(); (void)consume_i8();
    *var_at(t) = (int32_t)rotl32((uint32_t)*var_at(t), (uint32_t)*var_at(a));
    return 1;
  }
  case 0x27: { /* VariableRotateVariableRight */
    int32_t t = consume_i32(); (void)consume_i8(); int32_t a = consume_i32(); (void)consume_i8();
    *var_at(t) = (int32_t)rotr32((uint32_t)*var_at(t), (uint32_t)*var_at(a));
    return 1;
  }
  /* The jump cases below all share the pattern:
   *   address-from-var conditional jumps: read addr_var + cond_var, check cond, jump to addr_var value.
   *   constant-address conditional jumps:  read addr_const + cond_var, check cond, jump to addr_const.
   * For absolute jumps we set pc directly; for relative jumps we add to pc (the dispatch loop's
   * post-increment already happened via consume_i8, so 'relative' here means relative to *that*
   * post-opcode pc, matching the C++ VM's semantics). */
  case 0x28: { /* RelativeJumpToVariableAddressIfVariableGt0 */
    int32_t a_v = consume_i32(); (void)consume_i8(); int32_t c_v = consume_i32(); (void)consume_i8();
    if (*var_at(c_v) > 0) pc += *var_at(a_v);
    return 1;
  }
  case 0x29: { /* RelativeJumpToVariableAddressIfVariableLt0 */
    int32_t a_v = consume_i32(); (void)consume_i8(); int32_t c_v = consume_i32(); (void)consume_i8();
    if (*var_at(c_v) < 0) pc += *var_at(a_v);
    return 1;
  }
  case 0x2a: { /* RelativeJumpToVariableAddressIfVariableEq0 */
    int32_t a_v = consume_i32(); (void)consume_i8(); int32_t c_v = consume_i32(); (void)consume_i8();
    if (*var_at(c_v) == 0) pc += *var_at(a_v);
    return 1;
  }
  case 0x2b: { /* AbsoluteJumpToVariableAddressIfVariableGt0 */
    int32_t a_v = consume_i32(); (void)consume_i8(); int32_t c_v = consume_i32(); (void)consume_i8();
    if (*var_at(c_v) > 0) pc = *var_at(a_v);
    return 1;
  }
  case 0x2c: { /* AbsoluteJumpToVariableAddressIfVariableLt0 */
    int32_t a_v = consume_i32(); (void)consume_i8(); int32_t c_v = consume_i32(); (void)consume_i8();
    if (*var_at(c_v) < 0) pc = *var_at(a_v);
    return 1;
  }
  case 0x2d: { /* AbsoluteJumpToVariableAddressIfVariableEq0 */
    int32_t a_v = consume_i32(); (void)consume_i8(); int32_t c_v = consume_i32(); (void)consume_i8();
    if (*var_at(c_v) == 0) pc = *var_at(a_v);
    return 1;
  }
  case 0x2e: { /* RelativeJumpIfVariableGt0 */
    int32_t c_v = consume_i32(); (void)consume_i8(); int32_t addr = consume_i32();
    if (*var_at(c_v) > 0) pc += addr;
    return 1;
  }
  case 0x2f: { /* RelativeJumpIfVariableLt0 */
    int32_t c_v = consume_i32(); (void)consume_i8(); int32_t addr = consume_i32();
    if (*var_at(c_v) < 0) pc += addr;
    return 1;
  }
  case 0x30: { /* RelativeJumpIfVariableEq0 */
    int32_t c_v = consume_i32(); (void)consume_i8(); int32_t addr = consume_i32();
    if (*var_at(c_v) == 0) pc += addr;
    return 1;
  }
  case 0x31: { /* AbsoluteJumpIfVariableGt0 */
    int32_t c_v = consume_i32(); (void)consume_i8(); int32_t addr = consume_i32();
    if (*var_at(c_v) > 0) pc = addr;
    return 1;
  }
  case 0x32: { /* AbsoluteJumpIfVariableLt0 */
    int32_t c_v = consume_i32(); (void)consume_i8(); int32_t addr = consume_i32();
    if (*var_at(c_v) < 0) pc = addr;
    return 1;
  }
  case 0x33: { /* AbsoluteJumpIfVariableEq0 */
    int32_t c_v = consume_i32(); (void)consume_i8(); int32_t addr = consume_i32();
    if (*var_at(c_v) == 0) pc = addr;
    return 1;
  }
  case 0x34: { /* UnconditionalJumpToAbsoluteAddress */
    int32_t addr = consume_i32();
    pc = addr;
    return 1;
  }
  case 0x35: { /* UnconditionalJumpToAbsoluteVariableAddress */
    int32_t a_v = consume_i32(); (void)consume_i8();
    pc = *var_at(a_v);
    return 1;
  }
  case 0x36: { /* UnconditionalJumpToRelativeAddress */
    int32_t addr = consume_i32();
    pc += addr;
    return 1;
  }
  case 0x37: { /* UnconditionalJumpToRelativeVariableAddress */
    int32_t a_v = consume_i32(); (void)consume_i8();
    pc += *var_at(a_v);
    return 1;
  }
  case 0x38: { /* CheckIfVariableIsInput -- no I/O behaviour tracking in standalone mode */
    (void)consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = 0;
    return 1;
  }
  case 0x39: { /* CheckIfVariableIsOutput -- ditto */
    (void)consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = 0;
    return 1;
  }
  case 0x3a: { /* LoadInputCountIntoVariable */
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = 0;
    return 1;
  }
  case 0x3b: { /* LoadOutputCountIntoVariable */
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = 0;
    return 1;
  }
  case 0x3c: { /* CheckIfInputWasSet -- always says "yes, the user CLI set it" */
    int32_t v = consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = (*var_at(v) != 0) ? 1 : 0;
    return 1;
  }
  case 0x3d: { /* PrintVariable */
    int32_t v = consume_i32(); (void)consume_i8(); int8_t as_char = consume_i8();
    if (as_char) putchar((int)*var_at(v) & 0xFF);
    else         printf("%d\n", *var_at(v));
    return 1;
  }
  case 0x3e: { /* SetStringTableEntry */
    int32_t slot = consume_i32();
    int16_t len = consume_i16();
    if (slot >= 0 && slot < STRING_TABLE_SIZE) {
      int n = len;
      if (n < 0) n = 0;
      if (n >= STRING_TABLE_ITEM_MAX) n = STRING_TABLE_ITEM_MAX - 1;
      memcpy(string_table[slot], &PROGRAM[pc], (size_t)n);
      string_table[slot][n] = '\0';
    }
    pc += (len < 0 ? 0 : len);
    return 1;
  }
  case 0x3f: { /* PrintStringFromStringTable */
    int32_t slot = consume_i32();
    if (slot >= 0 && slot < STRING_TABLE_SIZE) fputs(string_table[slot], stdout);
    return 1;
  }
  case 0x40: { /* LoadStringTableLimitIntoVariable */
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = STRING_TABLE_SIZE;
    return 1;
  }
  case 0x41: { /* LoadStringTableItemLengthLimitIntoVariable */
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = STRING_TABLE_ITEM_MAX - 1;
    return 1;
  }
  case 0x42: { /* SetVariableStringTableEntry */
    int32_t slot_v = consume_i32(); (void)consume_i8();
    int16_t len = consume_i16();
    int slot = *var_at(slot_v);
    if (slot >= 0 && slot < STRING_TABLE_SIZE) {
      int n = len;
      if (n < 0) n = 0;
      if (n >= STRING_TABLE_ITEM_MAX) n = STRING_TABLE_ITEM_MAX - 1;
      memcpy(string_table[slot], &PROGRAM[pc], (size_t)n);
      string_table[slot][n] = '\0';
    }
    pc += (len < 0 ? 0 : len);
    return 1;
  }
  case 0x43: { /* PrintVariableStringFromStringTable */
    int32_t slot_v = consume_i32(); (void)consume_i8();
    int slot = *var_at(slot_v);
    if (slot >= 0 && slot < STRING_TABLE_SIZE) fputs(string_table[slot], stdout);
    return 1;
  }
  case 0x44: { /* LoadVariableStringItemLengthIntoVariable */
    int32_t slot_v = consume_i32(); (void)consume_i8(); int32_t dst = consume_i32(); (void)consume_i8();
    int slot = *var_at(slot_v);
    *var_at(dst) = (slot >= 0 && slot < STRING_TABLE_SIZE) ? (int32_t)strlen(string_table[slot]) : 0;
    return 1;
  }
  case 0x45: { /* LoadVariableStringItemIntoVariables -- writes characters into successive variables */
    int32_t slot_v = consume_i32(); (void)consume_i8(); int32_t dst = consume_i32(); (void)consume_i8();
    int slot = *var_at(slot_v);
    if (slot >= 0 && slot < STRING_TABLE_SIZE) {
      const char* s = string_table[slot];
      int dst_idx = dst;
      for (int i = 0; s[i] != '\0' && dst_idx + i < MEM_SIZE; ++i) {
        vars[dst_idx + i] = (int32_t)(unsigned char)s[i];
      }
    }
    return 1;
  }
  case 0x46: { /* LoadStringItemLengthIntoVariable */
    int32_t slot = consume_i32(); int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = (slot >= 0 && slot < STRING_TABLE_SIZE) ? (int32_t)strlen(string_table[slot]) : 0;
    return 1;
  }
  case 0x47: { /* LoadStringItemIntoVariables */
    int32_t slot = consume_i32(); int32_t dst = consume_i32(); (void)consume_i8();
    if (slot >= 0 && slot < STRING_TABLE_SIZE) {
      const char* s = string_table[slot];
      for (int i = 0; s[i] != '\0' && dst + i < MEM_SIZE; ++i) {
        vars[dst + i] = (int32_t)(unsigned char)s[i];
      }
    }
    return 1;
  }
  case 0x48: { /* PushVariableOnStack -- stack id is ignored in standalone runtime */
    (void)consume_i32(); (void)consume_i8();
    int32_t v = consume_i32(); (void)consume_i8();
    push(*var_at(v));
    return 1;
  }
  case 0x49: { /* PushConstantOnStack */
    (void)consume_i32(); (void)consume_i8();
    int32_t c = consume_i32();
    push(c);
    return 1;
  }
  case 0x4a: { /* PopVariableFromStack */
    (void)consume_i32(); (void)consume_i8();
    int32_t v = consume_i32(); (void)consume_i8();
    *var_at(v) = pop();
    return 1;
  }
  case 0x4b: { /* PopTopItemFromStack */
    (void)consume_i32(); (void)consume_i8();
    (void)pop();
    return 1;
  }
  case 0x4c: { /* CheckIfStackIsEmpty */
    (void)consume_i32(); (void)consume_i8();
    int32_t dst = consume_i32(); (void)consume_i8();
    *var_at(dst) = (stack_top == 0) ? 1 : 0;
    return 1;
  }
  case 0x4d: { /* CallSubroutine (stubbed) */
    (void)consume_i8(); /* id */
    int8_t in_arity = consume_i8();
    int8_t out_arity = consume_i8();
    /* Skip the per-argument payload (5 bytes each) so the dispatch loop stays
     * aligned -- we just don't execute the callee, since we don't ship a
     * subroutine library with the standalone program. */
    pc += (in_arity + out_arity) * 5;
    fprintf(stderr, "warning: CallSubroutine (id=%d) not implemented in the generated runtime\n", (int)PROGRAM[pc - 3]);
    return 1;
  }
  default:
    fprintf(stderr, "warning: unknown opcode 0x%02x at pc=%d (skipping rest of program)\n",
            (unsigned)(uint8_t)op, pc - 1);
    return 0;
  }
}

static void usage(const char* prog) {
  fprintf(stderr, "Usage: %s [--var IDX=VAL ...] [--steps N]\n", prog);
  fprintf(stderr, "  --var IDX=VAL   Set vars[IDX] = VAL (VAL accepts 0x hex prefix).\n");
  fprintf(stderr, "                  ':' is also accepted as a separator instead of '='.\n");
  fprintf(stderr, "  --steps N       Max VM steps before bailing out (default %d).\n", MAX_STEPS);
}

int main(int argc, char** argv) {
  memset(vars, 0, sizeof(vars));
  memset(stack, 0, sizeof(stack));
  for (int i = 0; i < STRING_TABLE_SIZE; ++i) string_table[i][0] = '\0';
  srand((unsigned)time(NULL));

  long max_steps = MAX_STEPS;
  for (int i = 1; i < argc; ++i) {
    if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
      usage(argv[0]);
      return 0;
    }
    if (strcmp(argv[i], "--var") == 0 && i + 1 < argc) {
      char* arg = argv[++i];
      char* sep = strchr(arg, '=');
      if (sep == NULL) sep = strchr(arg, ':');
      if (sep == NULL) {
        fprintf(stderr, "--var expects IDX=VAL (got '%s')\n", arg);
        return 1;
      }
      *sep = '\0';
      long idx = strtol(arg, NULL, 0);
      long val = strtol(sep + 1, NULL, 0);
      *sep = '=';
      if (idx < 0 || idx >= MEM_SIZE) {
        fprintf(stderr, "--var idx %ld out of range [0, %d)\n", idx, MEM_SIZE);
        return 1;
      }
      vars[idx] = (int32_t)val;
      continue;
    }
    if (strcmp(argv[i], "--steps") == 0 && i + 1 < argc) {
      max_steps = strtol(argv[++i], NULL, 0);
      if (max_steps <= 0) max_steps = MAX_STEPS;
      continue;
    }
    fprintf(stderr, "unknown argument '%s'\n", argv[i]);
    usage(argv[0]);
    return 1;
  }

  for (long s = 0; s < max_steps; ++s) {
    if (!step()) break;
  }

  printf("--- variable dump ---\n");
  for (int i = 0; i < MEM_SIZE; ++i) {
    printf("vars[%2d] = %11d  (0x%08x)\n", i, vars[i], (unsigned)vars[i]);
  }
  return 0;
}
)CTEMPLATE";

void substitute(std::string& s, const std::string& placeholder, const std::string& value) {
  // Single-pass replace-all. The template was authored so each placeholder appears
  // exactly once, but we still loop to keep this defensive against future template
  // edits that might re-use a placeholder.
  std::string::size_type pos = 0;
  while ((pos = s.find(placeholder, pos)) != std::string::npos) {
    s.replace(pos, placeholder.size(), value);
    pos += value.size();
  }
}

} // namespace

std::string ProgramCCodeGenerator::generate(const std::vector<unsigned char>& bytecode,
                                             const Options& options) {
  const uint32_t mem_size =
      options.memory_variables == 0 ? kDefaultMemoryVariables : options.memory_variables;
  const uint32_t stack_size =
      options.stack_capacity == 0 ? kDefaultStackCapacity : options.stack_capacity;
  const uint32_t max_steps =
      options.max_steps == 0 ? kDefaultMaxSteps : options.max_steps;

  std::string banner;
  if (!options.source_description.empty()) {
    // Wrap the description into the top comment so the generated file is self-describing.
    // The leading " *" plus space matches the surrounding comment style in the template.
    std::ostringstream b;
    std::istringstream lines(options.source_description);
    std::string line;
    while (std::getline(lines, line)) {
      b << " * " << line << "\n";
    }
    banner = b.str();
  }

  std::string out = kCRuntimeTemplate;
  substitute(out, "{{BANNER}}", banner);
  substitute(out, "{{MEM_SIZE}}", std::to_string(mem_size));
  substitute(out, "{{STACK_SIZE}}", std::to_string(stack_size));
  substitute(out, "{{MAX_STEPS}}", std::to_string(max_steps));
  substitute(out, "{{PROGRAM_BYTES}}",
             bytecode.empty() ? std::string("  0x00") : renderBytecodeArray(bytecode));
  return out;
}

} // namespace beast
